# Generated by Django 5.1.2 on 2024-11-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="security_clearance",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the employee has gone through clearance process",
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="type_of_work",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the employee is able to work on projects on ethical grounds.",
            ),
        ),
    ]
