# Generated by Django 5.1.2 on 2024-11-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "project",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "required_skills",
                    models.TextField(
                        help_text="List of required, separated by commas."
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("type_of_work", models.CharField(max_length=50)),
                (
                    "start_date",
                    models.DateField(help_text="date when the project starts"),
                ),
                ("security_clearance", models.CharField(max_length=50)),
                ("team_size", models.IntegerField(max_length=50)),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
    ]
