# Generated by Django 5.1.2 on 2024-11-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teams",
            name="experience",
            field=models.PositiveIntegerField(
                default=0, help_text="Years of experience"
            ),
        ),
        migrations.AlterField(
            model_name="teams",
            name="security_clearance",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the employee has gone through clearance process",
            ),
        ),
        migrations.AlterField(
            model_name="teams",
            name="type_of_work",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the employee is able to work on projects on ethical grounds.",
            ),
        ),
    ]
